In [1]:
import numpy as np

# Assignment: Computing H without for loops

Write python code to compute $\mathbf{H}$ and $\mathbf{b}$ given samples $\{(x_1, y_1), \cdots, (x_n, y_n)\}$ **without** for-loops.

>> def compute_H (X, Y) : -- returns 2 by 2 matrix H

>> def compute_b (X, Y) : -- returns 2 by 1 matrix b

X is an np.array of size N by 1, and Y is an np.array of size N by 1. They store the x and y values in correspondence order; X [i] is associated with Y[i].

Write code to also test your implementation by using synthetic data generated using known noisy model and estimating the parameters.



In [2]:
def compute_H (X, Y):
  sum_X = np.sum(X)
  return np.array( [[np.sum(np.square(X)), sum_X], [sum_X, len(X)]] )

def compute_b (X, Y):
  diff = np.sum(Y - X)
  return np.array( [[np.sum(diff * X)], [diff]] )

In [10]:
# Test using easy data first
X = np.array([1, 2, 3])
Y = np.array([3, 4, 5])
X, Y = X.reshape(-1, 1), Y.reshape(-1, 1)
print("H:\n", compute_H(X, Y))
print("b:\n", compute_b(X, Y))

H:
 [[14  6]
 [ 6  3]]
b:
 [[36]
 [ 6]]


In [6]:
# Test using synthetic data generated using Gaussian noise
# where N is the array length, mu is the mean, and sigma is the standard deviation of the Gaussian distribution
# using https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html
N, mu, sigma = 10, 0, 3
X = np.random.normal(mu, sigma, N)
Y = np.random.normal(mu, sigma, N)
X, Y = X.reshape(-1, 1), Y.reshape(-1, 1)
print("X:\n", X, "\nY:\n", Y)

# Estimating the parameters using computed H and b
H, b = compute_H(X, Y), compute_b(X, Y)
params = np.dot(np.linalg.inv(H), b)
print("H:\n", H, "\nb:\n", b, "\nParameters:\n", params)

X:
 [[-4.51750141]
 [-1.32851375]
 [-0.19815319]
 [ 2.30772542]
 [ 5.48092513]
 [-3.37272548]
 [-4.17339496]
 [-0.79264183]
 [ 3.77264085]
 [-0.87509671]] 
Y:
 [[ 5.15274651]
 [ 2.79446323]
 [-1.89295907]
 [ 1.77924055]
 [ 0.83021609]
 [ 2.34348791]
 [ 2.49118042]
 [-3.65869244]
 [-0.80223349]
 [-1.79174206]]
H:
 [[101.9975663   -3.69673594]
 [ -3.69673594  10.        ]] 
b:
 [[-40.45132454]
 [ 10.9424436 ]] 
Parameters:
 [[-0.36177916]
 [ 0.96050416]]
